parameters:
    inline_sections: ['keywords']

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symplify\ComposerJsonManipulator\:
        resource: '../src'

    Symplify\SmartFileSystem\SmartFileSystem: null
    Symplify\PackageBuilder\Reflection\PrivatesCaller: null
