parameters:
    inline_sections: ['keywords']

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symplify\ComposerJsonManipulator\:
        resource: '../src'

    Symfony\Component\Filesystem\Filesystem: null
    Symplify\PackageBuilder\Reflection\PrivatesCaller: null
